title:             Innovation
header-img:        img/simple-back.
email:             jamesbrother@gmail.com
copyright_name:    "Seongjin Lee"
description:       "The New Start"
baseurl:           "" 
url:               "http://resourceful.github.io" 
twitter_username:  _mak3r
github_username:   resourceful
facebook_username: seongjin.lee.18
email_username:    jamesbrother@gmail.com
linkedin_username: seongjin-lee-2677061b
google_scholar_username: mzWSzNAAAAAJ


# google_tracking_id: 

future:            true

# Build settings
markdown:          kramdown
# highlighter:       rouge
# permalink:         pretty
paginate:          15

exclude: ["less", "node_modules", "Grunfile.js", "package.json", "README.md", "contact.html", "tags.html", "categories.html", "Gemfile", "Gemfile.lock"]

#sass:
#  style:compressed

gems:
  - jekyll-feed
  - jekyll-paginate

#collections:
#    classes:
#        output:      true
#        permalink:   /classes/:path/